name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: setup-mkosi
        uses: systemd/mkosi@v24.3
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          ./build-server.sh
